# environement de travail avec node js
FROM node:13.12.0-alpine as build
# dossier dans lequel on va travailler 
WORKDIR /app
# ajouter un node mod pour etre executer 
ENV PATH /app/node_modules/.bin:$PATH
# equivalent du npm i avec le package lock
COPY package.json ./
COPY package-lock.json ./
COPY public ./public
COPY src ./src
COPY tsconfig.json ./
COPY .eslintrc.json ./
RUN npm ci
RUN npm install react-scripts
RUN npm run build

# environnement avec nginx
FROM nginx:stable-alpine
# copier le build du premier container dans le deuxieme
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
